--
-- See doc/doc.md for an introduction.
--
-- the database schema is in the file .a-schema.sql, or you can
-- query it from with the sqlite3 shell using ".schema"
--

--
-- write a SQL query to count the number of rooms in each zone
-- of the world, showing the largest zones first (use the zone name as a
-- tie-breaker).
--
