--
-- write a query to list courses with prereqs. most of the information
-- should come from the course, with just the prereq_id added for
-- the course's prereq. sort by course_id.
--
-- this will require joining the tables course and prereq.
-- use the JOIN syntax, not a comma-separated list of tables.
--
-- the output should look like:
--
--   course_id   title       dept_name   credits     prereq_id
--   ----------  ----------  ----------  ----------  ----------
--   BIO-301     Genetics    Biology     4           BIO-101
--   BIO-399     Computatio  Biology     3           BIO-101
--   CS-190      Game Desig  Comp. Sci.  4           CS-101
--   CS-315      Robotics    Comp. Sci.  3           CS-101
--   CS-319      Image Proc  Comp. Sci.  3           CS-101
--   CS-347      Database S  Comp. Sci.  3           CS-101
--   EE-181      Intro. to   Elec. Eng.  3           PHY-101
--
-- write your query on the next line


--
-- write a query to list the departments that have courses
-- with prereqs and how many such courses each department has.
-- sort them from more prereqs to fewer.
--
-- the output should look like:
--
--   dept_name   prereqs
--   ----------  ----------
--   Comp. Sci.  4
--   Biology     2
--   Elec. Eng.  1
--
-- write your query on the next line


--
-- write a query with output similar to the previous one, but include the
-- title of the prereq course as well. this will require joining
-- on courses two times--once to get the info about the main course, and
-- a second time to get the title of the prereq.
--
-- the output should look like:
--
--   course_id   title       dept_name   credits     prereq_id   prereq_title
--   ----------  ----------  ----------  ----------  ----------  -----------------
--   BIO-301     Genetics    Biology     4           BIO-101     Intro. to Biology
--   BIO-399     Computatio  Biology     3           BIO-101     Intro. to Biology
--   CS-190      Game Desig  Comp. Sci.  4           CS-101      Intro. to Compute
--   CS-315      Robotics    Comp. Sci.  3           CS-101      Intro. to Compute
--   CS-319      Image Proc  Comp. Sci.  3           CS-101      Intro. to Compute
--   CS-347      Database S  Comp. Sci.  3           CS-101      Intro. to Compute
--   EE-181      Intro. to   Elec. Eng.  3           PHY-101     Physical Principl
--
-- write your query on the next line

