--
-- write a SQL query to list the total salary budget for each
-- department, starting with the most expensive department
-- note: this only needs to involve the instructor table
--
-- the database schema is in the file .a-schema.sql, or you can
-- query it from within the sqlite3 shell using ".schema instructor"
--
-- the output should look like:
--
--   dept_name   total_budget
--   ----------  ------------
--   Comp. Sci.  232000
--   Physics     182000
--   Finance     170000
--   History     122000
--   Elec. Eng.  80000
--   Biology     72000
--   Music       40000
--
-- write your query on the next line
SELECT dept_name, SUM(salary) AS total_budget FROM instructor GROUP BY dept_name ORDER BY total_budget DESC;

--
-- write a query to list the total number of classes taught in each
-- semester. The list should be sorted by year, with semester used as
-- a tie breaker
--
-- the output should look like:
--
--   semester    year        total_classes
--   ----------  ----------  -------------
--   Fall        2017        3            
--   Spring      2017        3            
--   Summer      2017        1            
--   Spring      2018        7            
--   Summer      2018        1            
SELECT semester, year, COUNT(1) AS total_classes FROM teaches GROUP BY year, semester ORDER BY year, semester;
