--
-- write a SQL query to delete all students who have ever failed a class or
-- who have never taken a class.
--
-- note that the the schema for "takes" has cascading deletes, so this will
-- also delete all records of the affected students taking classes.
--
-- this should be a single DELETE query and there should be no output.
--
-- write your query here
--
