--
-- this query examines the remaining students to see if your delete worked
-- you should not edit this file
--
-- the output should look like:
--
--   ID          name        dept_name   tot_cred
--   ----------  ----------  ----------  ----------
--   00128       Zhang       Comp. Sci.  102
--   12345       Shankar     Comp. Sci.  32
--   19991       Brandt      History     80
--   23121       Chavez      Finance     110
--   44553       Peltier     Physics     56
--   54321       Williams    Comp. Sci.  54
--   55739       Sanchez     Music       38
--   76543       Brown       Comp. Sci.  58
--   76653       Aoi         Elec. Eng.  60
--   98765       Bourikas    Elec. Eng.  98
--
SELECT * FROM student ORDER BY id;
