-- write a query to calculate the “Bacon number” for all people in the database
-- a person's Bacon number tells how many steps removed that person is from Kevin Bacon
--
-- Kevin Bacon has a Bacon number of 0
-- anyone who worked on a film with Kevin Bacon has a Bacon number of 1
-- anyone who worked on a film with someone with a Bacon number of 1 has a
-- Bacon number of 2, and so forth.
--
-- return each person's id, name, and Bacon number
-- ignore anyone with a Bacon number over 4
-- sort the results from smallest to largest Bacon number
-- sort by name as the tie breaker
--
-- Use a recursive common table expression with the following strategy:
-- * Start with Kevin Bacon and assign him number 0
-- * Add anyone working on a film with someone in the result set, assigning
--   them the other person's number plus one
-- * Do not add any new results greater than 4
-- * Once finished, find the smallest Bacon number for each person for
--   the final result list
--
-- The output should look like:
--   
--   +-----------+-----------------------------------+---+
--   | person_id |               name                | n |
--   +-----------+-----------------------------------+---+
--   | 102       | Kevin Bacon                       | 0 |
--   | 815070    | Aaron Sorkin                      | 1 |
--   | 718031    | Al Reinert                        | 1 |
--   | 770650    | Andrew Scheinman                  | 1 |
--   | 1005420   | Ashley Miller                     | 1 |
--   | 1469      | Barry Levinson                    | 1 |
--   | 200       | Bill Paxton                       | 1 |
--   | 93        | Brad Pitt                         | 1 |
--   | 1338      | Brian Helgeland                   | 1 |
--   | 1741      | Bryan Singer                      | 1 |
--   ...
--   | 115310    | William Broyles Jr.               | 1 |
--   | 826714    | Zack Stentz                       | 1 |
--   | 704031    | A.J. Quinnell                     | 2 |
--   | 1173      | Aaron Eckhart                     | 2 |
--   | 830760    | Aaron Stockard                    | 2 |
--   | 1093951   | Aaron Taylor-Johnson              | 2 |
--   | 180411    | Abbie Cornish                     | 2 |
--   | 570912    | Adam McKay                        | 2 |
--   | 1490      | Adrian Lyne                       | 2 |
--   | 93501     | Adriano Bolzoni                   | 2 |
--   ...
--
-- write your query here:
